### ISSUE TITLE
The version 7.2.2 does not work with Express

### ISSUE THREAD

**Issue by janbodnar** [harttle/liquidjs#106]
I have just tried Liquid 7.2.2 with Express 4.16.4 and the example failed with the following error:
...\express_app\node_modules\liquidjs\dist\liquid.common.js:2146
        this.cache = {};
                   ^

TypeError: Cannot set property 'cache' of undefined
    at Liquid (C:\Users\Jano\Documents\dom\dataset\express_app\node_modules\liquidjs\dist\liquid.common.js:2146:20)
    at Object.<anonymous> (C:\Users\Jano\Documents\dom\dataset\express_app\index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)

In version 6.4.2, the example works OK.

```
const express = require("express");
const path = require("path");
const Liquid = require('liquidjs');

const engine = Liquid();
const app = express();

app.engine('liquid', engine.express());
app.set('views', path.resolve(__dirname, "views"));
app.use("/public", express.static(__dirname + "/public"));
app.set('view engine', 'liquid');

app.get("/words", (req, res) => {

    const words = ['coin', 'marble', 'forest', 'falcon', 'mountain'];
    const data = words.join(', ');

    res.render("home", { data });
});

app.use((req, res) => {
    res.statusCode = 404;
    res.end("404 - page not found");
});

app.listen(3000, () => {

    console.log("Application started on port 3000");
})
```

**Comment by harttle** [comment]
That's a break change introduced in version 7, here's a changelog: https://github.com/harttle/liquidjs/blob/master/CHANGELOG.md#breaking-changes-1 Hope it helps!

**Comment by janbodnar** [comment]
Ah, OK. Thanks for clarifying. I wrote a beginning tutorial on Liquid a fortnight ago 
[Liquid tutorial](http://zetcode.com/javascript/liquidjs/)
I am going to quickly update it.
