### ISSUE TITLE
CLI errors immediately

### ISSUE THREAD

**Issue by brandonpittman** [harttle/liquidjs#169]
Tried the CLI, but it's not working.

```
❯ echo '{{"hello" | capitalize}}' | npx liquidjs
npx: installed 1 in 3.236s
(node:85312) UnhandledPromiseRejectionWarning: TypeError: Liquid is not a constructor
    at render (/Users/brandonpittman/.npm/_npx/85312/lib/node_modules/liquidjs/bin/liquid.js:10:18)
    at Socket.<anonymous> (/Users/brandonpittman/.npm/_npx/85312/lib/node_modules/liquidjs/bin/liquid.js:7:31)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:85312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by FickleLife** [comment]
I am currently getting `TypeError: Liquid is not a constructor`, am running on a serverless Glitch function. version is 9.11.10. 

code is

```
const Liquid = require('liquidjs');
const path = require('path');

const transformWeather = (data) => {
  const engine = new Liquid({
    root: path.resolve(__dirname, 'liquid/'),  
    extname: '.liquid'
  });

  engine
    .renderFile('wwo', data)
    .then(console.log)
}
```

Any clues why this would be happening?

**Comment by harttle** [comment]
Use `const {Liquid} = require('liquidjs');` instead.
