### ISSUE TITLE
TypeError: Cannot read property 'prev' of undefined

### ISSUE THREAD

**Issue by paulrobertlloyd** [harttle/liquidjs#200]
Since the 9.10.0 release, I get this error in 11ty when LiquidJS’s `cache` option is set to `true`:

```bash
Error writing templates: (more in DEBUG output)
> Having trouble writing template: www/archive/index.html

`TemplateWriterWriteError` was thrown
> Cannot read property 'prev' of undefined, file:src/_layouts/index.liquid, line:1, col:1

`RenderError` was thrown
> Cannot read property 'prev' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'prev' of undefined
        at LRU.remove (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/liquidjs/dist/liquid.cjs.js:281:14)
        at LRU.ensureLimit (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/liquidjs/dist/liquid.cjs.js:294:18)
        at LRU.write (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/liquidjs/dist/liquid.cjs.js:269:14)
        at Liquid._parseFile (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/liquidjs/dist/liquid.cjs.js:2527:23)
        at _parseFile.next (<anonymous>)
        at reduce (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/liquidjs/dist/liquid.cjs.js:2437:25)
        at async TemplateLayout.render (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/TemplateLayout.js:135:25)
        at async Template.renderPageEntry (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/Template.js:537:17)
        at async Template.writeMapEntry (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/Template.js:556:21)
        at async Promise.all (index 1022)
```

It doesn’t seem to be one single template causing this issue either; commenting out lines has the error appear against other templates. Any clues why this might be happening?

**Comment by harttle** [comment]
I find [a similar case](https://github.com/harttle/liquidjs/commit/6de933897e3347bd526a97434ebc6fa1b96f2ae0#diff-7a5fc2fdc2d1f713ff3e9a88320b2f36R103-R122) as yours and now it passes in liquidjs@9.11.1. Please let me know if that fixes your trouble.

**Comment by paulrobertlloyd** [comment]
@harttle Awesome. Will see if this fix works. Thanks again!

**Comment by paulrobertlloyd** [comment]
Oops, never got back to you on this. Yup, all works, so closing issue.
