### ISSUE TITLE
case statement with multiple values does not work

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [harttle/liquidjs#355]
See following example:

```liquid
{% case "asd" %}
{% when  "test", "asd" %}
should work, but its not
{% endcase %}
```

Produces:

```ParseError: unexpected token at ", \"asd\"", line:1, col:1```

But actually it should be supported to add multiple values: https://liquidjs.com/tags/case.html

**Comment by harttle** [comment]
It's supported since v1.9.1, check your version please. See the playground demo: https://liquidjs.com/playground.html#eyUgY2FzZSAiYXNkIiAlfQ0KeyUgd2hlbiAgInRlc3QiLCAiYXNkIiAlfQ0Kc2hvdWxkIHdvcmssIGJ1dCBpdHMgbm90DQp7JSBlbmRjYXNlICV9

**Comment by pdehaan** [comment]
Interesting. I'm seeing errors in liquidjs@6.4.3 (the current version in Eleventy v0.12).

```js
const Liquid = require('liquidjs'); // v6.4.3
const engine = Liquid();

const {name, version} = require("liquidjs/package.json");
console.log("DEBUG:", `${name}@${version}`);

const tmpl = `
  {% case "asd" %}
    {% when "test", "asd" %}
      should work, but its not
    {% when "foo" %}
      foo
  {% endcase %}
`;

engine
    .parseAndRender(tmpl)
    .then(console.log);
```

```sh
> node foo.liquid.js

DEBUG: liquidjs@6.4.3
(node:11247) UnhandledPromiseRejectionWarning:    1| 
>> 2|   {% case "asd" %}
   3|     {% when "test", "asd" %}
   4|       should work, but its not
   5|     {% when "foo" %}

RenderError: cannot eval '"test", "asd"' as value, line:2
    at Object._callee2$ (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:1681:21)
    at tryCatch (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:108:40)
    at Generator.invoke [as _invoke] (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:319:22)
    at Generator.prototype.<computed> [as throw] (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:156:21)
    at step (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:25:30)
    at /private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:38:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
From TypeError: cannot eval '"test", "asd"' as value
    at evalValue (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:1580:9)
    at Function.evalExp (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:1567:10)
    at Object.render (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:2351:26)
    at Object._callee$ (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:1851:55)
    at tryCatch (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:108:40)
    at Generator.invoke [as _invoke] (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:319:22)
    at Generator.prototype.<computed> [as next] (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:156:21)
    at step (/private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:25:30)
    at /private/tmp/liquid-case/node_modules/liquidjs/dist/liquid.common.js:43:14
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---

But, it does seem to work in liquidjs@9.25.0 (current latest stable):

```js
const { Liquid } = require('liquidjs');
const engine = new Liquid();

const tmpl = `
  {% case "asd" %}
    {% when "test", "asd" %}
      should work, but its not
  {% endcase %}
`;

engine
    .parseAndRender(tmpl)
    .then(console.log);
```

**Comment by pdehaan** [comment]
Ah, it looks like the multiple "when" clause support was added in 9.25.0, per #343.
