### ISSUE TITLE
section tag not found, does anyone knows how to go to sections  directory to read liquid file when use liquidjs with theme of shopify

### ISSUE THREAD

**Issue by Phong111222** [harttle/liquidjs#370]

**Comment by Phong111222** [comment]
This is the error when i try to read the liquid file that have section tag in theme that i downloaded from shopify

tag "section" not found, file:E:\shopify-learn\simple-next-shopify\src\views\template\templates\product.liquid, line:1, col:1
>> 1| {% section 'product-template' %}
   2|
ParseError: tag "section" not found, file:E:\shopify-learn\simple-next-shopify\src\views\template\templates\product.liquid, line:1, col:1
    at Parser.parseToken (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1786:19)
    at Parser.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1771:33)
    at Liquid.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2957:28)
    at Liquid._parseFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2998:30)
    at _parseFile.next (<anonymous>)
    at reduce (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1685:25)
    at async Liquid.renderFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:3012:27)
    at async getServerSideProps (E:\shopify-learn\simple-next-shopify\.next\server\pages\index.js:51:16)
    at async renderToHTML (E:\shopify-learn\simple-next-shopify\node_modules\next\dist\next-server\server\render.js:39:215)
    at async E:\shopify-learn\simple-next-shopify\node_modules\next\dist\next-server\server\next-server.js:112:97
From AssertionError: tag "section" not found
    at assert (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:949:15)
    at TagMap.get (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2917:9)
    at new Tag (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1727:34)
    at Parser.parseToken (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1778:24)
    at Parser.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1771:33)
    at Liquid.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2957:28)
    at Liquid._parseFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2998:30)
    at _parseFile.next (<anonymous>)
    at reduce (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1685:25)
    at async Liquid.renderFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:3012:27) {
  originalError: AssertionError: tag "section" not found
      at assert (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:949:15)
      at TagMap.get (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2917:9)
      at new Tag (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1727:34)
      at Parser.parseToken (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1778:24)
      at Parser.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1771:33)
      at Liquid.parse (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2957:28)
      at Liquid._parseFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:2998:30)
      at _parseFile.next (<anonymous>)
      at reduce (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:1685:25)
      at async Liquid.renderFile (E:\shopify-learn\simple-next-shopify\node_modules\liquidjs\dist\liquid.node.cjs.js:3012:27),
  token: TagToken {
    kind: 4,
    input: "{% section 'product-template' %}\n",
    begin: 0,
    end: 32,
    file: 'E:\\shopify-learn\\simple-next-shopify\\src\\views\\template\\templates\\product.liquid',
    trimLeft: false,
    trimRight: false,
    content: "section 'product-template'",
    name: 'section',
    args: "'product-template'"
  },
  context: ">> 1| {% section 'product-template' %}\n   2| "
}

**Comment by harttle** [comment]
Duplicate with #116
