### ISSUE TITLE
Installation Error: LiquidJS

### ISSUE THREAD

**Issue by GithubyAdarsh** [harttle/liquidjs#484]
#Node - v17.6.0
Tell Me What To Do, I Chose LiquidJS Because I'm familiar with Jinja In Flask (Python Package)
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path D:\travse\Express Side\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\travse\Express Side\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\travse\\Express Side\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.6.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\travse\Express Side\node_modules\which\which.js:13:12)  
npm ERR! gyp verb `which` failed     at F (D:\travse\Express Side\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\travse\Express Side\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\travse\Express Side\node_modules\which\which.js:13:12)  
npm ERR! gyp verb `which` failed     at F (D:\travse\Express Side\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\travse\Express Side\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\travse\Express Side\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python D:\travse\environment\Scripts\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: D:\travse\environment\Scripts\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:688:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\travse\\Express Side\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" 
npm ERR! gyp ERR! cwd D:\travse\Express Side\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.6.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goura\AppData\Local\npm-cache\_logs\2022-02-26T14_50_46_839Z-debug-0.log
```

**Comment by GithubyAdarsh** [comment]
I deleted ```package.json``` all files in the directory and rerun ```npm init -y``` then, it works
now and generated essentials using ```npx express-generator --no-view --css sass```. It was happening because I was first installing `express` and `sass` then `liquidjs`. But now I first installed `liquidjs` and other dependencies

Thank You 😁
