### ISSUE TITLE
Error launching nodejs - v0.12.7

### ISSUE THREAD

**Issue by stevenanthonyrevo** [harttle/liquidjs#55]
Getting an error when loading my application. I've tried reinstalling the library and it didn't solve this. Would you be able to look into this?  

```
liquidjs/index.js:47
      .then(() => this.parse(html))
             ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (app.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Thanks!

**Comment by stevenanthonyrevo** [comment]
Updated to node v9.3.0 and had success!

**Comment by harttle** [comment]
It's works in Node.js >= 4, see: https://github.com/harttle/liquidjs/blob/master/.travis.yml#L3-L5
