### ISSUE TITLE
Error When Accessing Subproperty of Bracketed Reference

### ISSUE THREAD

**Issue by gtowne** [harttle/liquidjs#643]
I'm seeing what appears to be a parsing error when trying to access a subproperty of an object where the top-level key is wrapped in brackets. [Here](https://liquidjs.com/playground.html#e3sgWyJLZXkgU3RyaW5nIHdpdGggU3BhY2VzIl0uc3VicHJvcGVydHlfa2V5IH19,ewogICAgIktleSBTdHJpbmcgd2l0aCBTcGFjZXMiOiB7CiAgICAgICJzdWJwcm9wZXJ0eV9rZXkiOiAic3VicHJvcGVydHktdmFsdWUiCiAgICB9Cn0=) a minimal repro in the LiquidJS playground that demonstrates the error.

### Template Value
`{{ ["Key String with Spaces"].subproperty_key }}`

### Scope Object
``` Javascript
{
    "Key String with Spaces": {
      "subproperty_key": "subproperty-value"
    }
}
```

### Expected Result
```
subproperty-value
```

### Actual Result
```
expected "|" before filter, line:1, col:30, line:1, col:1
>> 1| {{ ["Key String with Spaces"].subproperty_key }}
      ^
ParseError: expected "|" before filter, line:1, col:30, line:1, col:1
    at ae.te [as constructor] (https://liquidjs.com/js/liquid.browser.min.js:1:5364)
    at new ae (https://liquidjs.com/js/liquid.browser.min.js:1:5755)
    at Nr.parseToken (https://liquidjs.com/js/liquid.browser.min.js:1:42812)
    at Nr.parseTokens (https://liquidjs.com/js/liquid.browser.min.js:1:42552)
    at Nr.parse (https://liquidjs.com/js/liquid.browser.min.js:1:42459)
    at P.parse (https://liquidjs.com/js/liquid.browser.min.js:1:72666)
    at P._parseAndRender (https://liquidjs.com/js/liquid.browser.min.js:1:73244)
    at P.<anonymous> (https://liquidjs.com/js/liquid.browser.min.js:1:73405)
    at Object.next (https://liquidjs.com/js/liquid.browser.min.js:1:2090)
    at https://liquidjs.com/js/liquid.browser.min.js:1:1136
From expected "|" before filter, line:1, col:30
>> 1| {{ ["Key String with Spaces"].subproperty_key }}
                                   ^
TokenizationError: expected "|" before filter, line:1, col:30
    at ie.te [as constructor] (https://liquidjs.com/js/liquid.browser.min.js:1:5364)
    at new ie (https://liquidjs.com/js/liquid.browser.min.js:1:5623)
    at F.error (https://liquidjs.com/js/liquid.browser.min.js:1:32131)
    at F.assert (https://liquidjs.com/js/liquid.browser.min.js:1:32232)
    at F.readFilter (https://liquidjs.com/js/liquid.browser.min.js:1:29186)
    at F.readFilters (https://liquidjs.com/js/liquid.browser.min.js:1:29053)
    at F.readFilteredValue (https://liquidjs.com/js/liquid.browser.min.js:1:28926)
    at new Fr (https://liquidjs.com/js/liquid.browser.min.js:1:39501)
    at Nr.parseToken (https://liquidjs.com/js/liquid.browser.min.js:1:42738)
    at Nr.parseTokens (https://liquidjs.com/js/liquid.browser.min.js:1:42552)
```

**Comment by harttle** [comment]
Seems this works fine on shopify liquid. I'll treat this as a bug.

BTW, I noticed another problem: `line:1, col:30, line:1, col:1` , it's output twice by different level of code.

**Comment by gtowne** [comment]
Great, thanks for confirming! We have a workaround right now, but our workaround is a little ugly, so we'll be eagerly awaiting a fix. Let me know if there's anything more we can do to help with that.

**Comment by harttle** [comment]
Created a test case for this scenario: https://github.com/harttle/liquidjs/blob/942944eae0cc72efe3e12b42778de53d92f1ea4d/test/e2e/issues.spec.ts#L457-L466
